name: "CI - JDK 11 Build"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build-jdk11:
    name: "JDK 11 Build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: joschi/setup-jdk@68381f2c0646f942f70b69f8e81fe10e1ed5d293
        with:
          java-version: 11
      - name: Build
        run: mvn clean install
